### PR TITLE
Update PPP

### LINKED ISSUE #29: Create Skeletal PPP Kyriel

### PR DESCRIPTION
**Pull request by s-kybound**
Update my contributions for week 7 deliverables.

Resolves #29.

### CODE REVIEW

**Review by javinchua — CHANGES_REQUESTED** [review]
Please update your AboutUs.md file to be team/s-kybound.md

**Comment by s-kybound** [comment]
@javinchua amended

**Review by yongning0310 — APPROVED** [review]
good job at fixing the EOF error !

**Review by javinchua — APPROVED** [review]
LGTM

**Pull request merged**
